### ISSUE TITLE
Sidebar selection

### ISSUE THREAD

**Issue by alehandrof** [FMCorz/MoveTab#1] opened 2012-08-14 13:26 UTC
The sidebar loses the selection when moving tabs. This issue was fixed in a similar plugin that was posted in the forums some time ago:
http://www.sublimetext.com/forum/viewtopic.php?f=2&t=5897

**Comment by FMCorz** [comment] 2012-08-14 13:43
Hi, thanks for raising this point. I have tried to reproduce the bug you're mentioning but I can't. Could you tell me more where to look at?

Thanks!

**Comment by alehandrof** [comment] 2012-08-15 11:44
Let's say you have a couple tabs open. If you switch between them using Ctrl+Page Up/Down, the current tab is highlighted in the sidebar. If, however, you use the Ctrl+Shift+Page Up/Down to move the current tab, it stops being highlighted in the sidebar. I don't know how explain this better. Looking back over the forum thread, a fix seems to be to add `self.window.focus_view(view)` on line 49.

**Comment by FMCorz** [comment] 2012-08-16 08:12
I have tested with the latest version of Sublime on Ubuntu and MacOS and I can't reproduce it, can you?

**Comment by alehandrof** [comment] 2012-08-20 06:21
![](http://i.imgur.com/zlAOv.png)

The screenshot is from Ubuntu 12.04. It's a little tricky to capture, because it looks as if Alt+Tab out of Sublime, when I return, the highlight appears (and is therefore captured on a screenshot). Do you maybe want me to grab a screencast so you can see what's going in more detail?

**Comment by FMCorz** [comment] 2012-08-24 10:15
Thanks a lot for your report. I was looking at the project sidebar and did not think about the Open Files one. It is now fixed. Cheers! \o/

**Closed as completed by FMCorz** 2012-08-24 10:15 UTC
